### ISSUE TITLE
python module onnx was not found

### ISSUE THREAD

**Issue by JonathanChiang** [onnx/onnx-r#1]
Is there a way you are supposed to set the path of python configuration for R? 

 > library(onnx)
> node_def <- make_node("Relu", list("X"), list("Y"))
Error: Python module onnx was not found.

Detected Python configuration:

python:         /usr/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
version:        2.7.12 (default, Dec  4 2017, 14:50:18)  [GCC 5.4.0 20160609]
numpy:          /usr/lib/python2.7/dist-packages/numpy
numpy_version:  1.11.0
onnx:           [NOT FOUND]

python versions found: 
 /usr/bin/python
 /usr/bin/python3
 /home/jichiang/anaconda3/bin/python

**Comment by terrytangyuan** [comment]
Please take a look at this: https://rstudio.github.io/reticulate/articles/versions.html
