### ISSUE TITLE
Support for Saving Models

### ISSUE THREAD

**Issue by ankane** [onnx/onnx-r#2]
Hi, are there any plans to support saving models in ONNX format, similar to the [PMML](https://cran.r-project.org/web/packages/pmml/index.html) library? Something like:

```r
library(onnx)

model <- lm(Species ~ ., iris)
onnx(model)
```

**Comment by tja2000** [comment]
Hi, AFAIK the implementation uses Python in the background using reticular.
I am currently using Python more than R, but this code used to work last year. I don't think there is a native ONNX package in R for the moment.  

```
library(onnx)
library(reticulate)
onnx    <- import("onnx")
np      <- import("numpy",convert=FALSE)
backend <- import("onnx_tf.backend")

# We can then use the loaded numpy Python library to define a helper function to 
# load testing sample from numpy serialized archive.
load_npz_samples <- function(npz_path) {
  sample <- np$load(normalizePath(npz_path), encoding = 'bytes')
  
  #s1 <- sample$items()[[1]]
  inputvals =  sample$items()[[0]][[1]][[0]]
  outputvals = sample$items()[[1]][[1]]
  
  l <-  list(
    inputs = inputvals,
    outputs = outputvals
  )
  return(l)
}

# Finally, we can load the ONNX model and the testing samples, and then run 
# the model using ONNX TensorFlow backend:
  
# Specify paths to ONNX model and testing samples
onnx_model_dir <- paste(getwd(),"/data/resnet50",sep='')
model_pb_path  <- file.path(onnx_model_dir, "model.onnx")
npz_path       <- file.path(onnx_model_dir, "test_data_1.npz")

# Load ONNX model
model <- load_from_file(model_pb_path)

# Load testing sample from numpy serialized archive
samples           <- load_npz_samples(npz_path)
inputs            <- samples$inputs
expected_outputs  <- samples$outputs

# Run the model with an onnx backend
actual_outputs <- backend$run_model(model, inputs)

# The expected output should be the same as the actual, or nearly:
print(np$testing$assert_almost_equal(expected_outputs, actual_outputs))
```

**Comment by ankane** [comment]
Hey @tja2000, thanks for the quick response. That code appears to load an ONNX model rather than save one though.

**Comment by terrytangyuan** [comment]
@ankane No that won't be supported since `lm` itself needs to have an implementation in ONNX.

**Comment by terrytangyuan** [comment]
@tja2000 Thanks! Feel free to add anything you think useful to the tutorials.

**Comment by ankane** [comment]
@terrytangyuan Thanks for the response, but not sure I follow. The PMML package referenced above is able to save `lm` models as PMML, and ONNX-ML supports linear regression.

**Comment by terrytangyuan** [comment]
@ankane Even though "ONNX-ML supports linear regression", R's `lm` is different than `ONNX-ML`'s linear regression implementation.

**Comment by ankane** [comment]
The ONNX format seems flexible enough to support R's linear regression, as it supports scikit-learn's in Python. Anyways, it sounds like saving R models (not just `lm`) in the ONNX format isn't on the roadmap.

**Comment by terrytangyuan** [comment]
@ankane Yes I agree. Feel free to submit any PRs if you think it's straightforward to map between those different implementations. Personally I feel like it's a lot of work and not even sure if it's in demand yet. Thanks for the issue anyways!

**Comment by Patriol-LLC** [comment]
Sorry I still don't understand is it possible to export a machine learning model to onnx from R or should I just stick to Python?

**Comment by Patriol-LLC** [comment]
And if it is please show how.
